#ifndef POKEMONPROJECT_EXITCODES_H
#define POKEMONPROJECT_EXITCODES_H

#define EXIT_ERROR_SDL_INIT            1
#define EXIT_ERROR_SDL_WINDOW_CREATE   2
#define EXIT_ERROR_SDL_IMAGE_LOAD      3
#define EXIT_ERROR_SDL_RENDERER_CREATE 3

#endif